spring.application.name=stage-03-spring-crud

spring.h2.console.enabled=false

spring.datasource.url=jdbc:mysql://localhost:3306/spring_backend_study
spring.datasource.username=root
spring.datasource.password=${MYSQL_PASSWORD}
